# Generated by Django 5.0 on 2024-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhapp', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
