# Generated by Django 5.0 on 2024-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhapp', '0005_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
