# Generated by Django 5.0 on 2024-06-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhapp', '0006_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
