# Generated by Django 5.0.4 on 2024-06-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhapp', '0007_remove_customerorder_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='address',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='region',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='street_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='zip_code',
            field=models.TextField(blank=True),
        ),
    ]
