# Generated by Django 5.0 on 2024-10-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhapp', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
